config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    collection do
      get 'newest'
      get 'popular'
    end
  end
  resources :users, only:[:show]
  resources :comments, only:[:create]
  resources :likes, only:[:create, :destroy]
  resources :tags, param: :tag_name, only: [:index, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  #Associtation
  belongs_to :user
  belongs_to :prototype

  validates :text, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  #Association
  belongs_to :prototype, counter_cache: :likes_count
  belongs_to :user
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base

  # Association
  belongs_to :user
  has_many :thumbnails
  has_many :comments
  has_many :likes

  acts_as_taggable

  accepts_nested_attributes_for :thumbnails, reject_if: proc { |attributes| attributes['content'].blank? }

  #Default Paginatiton
  paginates_per 8


  def like_blank?(current_user)
    likes.find_by(user_id: current_user.id).blank?
  end
end

app/models/thumbnail.rb
class Thumbnail < ActiveRecord::Base
#Association
  belongs_to :prototype

  mount_uploader :content, ThumbnailUploader

  #Main,Subの区別
  enum status: %i(main sub)
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Association
  has_many :prototypes
  has_many :likes

  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: [:edit, :destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:name, :avatar, :group, :profile, :works)
    devise_parameter_sanitizer.for(:account_update).push(:name, :avatar, :group, :profile, :works)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @prototype = Prototype.find(create_params[:prototype_id])
    @prototype.comments.create(create_params)
  end

  private
  def create_params
    params.require(:comment).permit(:text, :prototype_id).merge(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @prototype = Prototype.find(params[:prototype_id])
    current_user.likes.create(prototype_id: params[:prototype_id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, prototype_id: params[:id]).destroy
    @prototype = Prototype.find(params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  def index
    @prototypes = Prototype.includes(:user).order(likes_count: :DESC).page(params[:page])
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
  end

  def new
    @prototype = Prototype.new
    @prototype.thumbnails.build
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)
    @prototype.save ? (redirect_to :root, success: 'プロトタイプが投稿されました') : (render :new, error: '投稿に失敗しました')
  end

  def edit
    @prototype = Prototype.find(params[:id])
  end

  def destroy
    prototype = Prototype.find(params[:id])
    if prototype.user_id == current_user.id
      prototype.destroy
      redirect_to :root, success: 'プロトタイプの削除に成功しました'
    end
  end

  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.user_id == current_user.id
      @prototype.update(prototype_params)
    end
    redirect_to :root, flash: {success: 'プロトタイプの編集に成功しました'}
  end

  def newest
    @prototypes = Prototype.includes(:user).order(created_at: :DESC).page(params[:page])
  end

  def popular
    @prototypes = Prototype.includes(:user).order(likes_count: :DESC).page(params[:page])
  end

  private
  def prototype_params
    params.require(:prototype).permit(:name, :copy, :concept, thumbnails_attributes:[:id,:content, :status]).merge(tag_list: params[:prototype][:tag])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.most_used(20)
  end

  def show
    @prototypes = Prototype.tagged_with(params[:tag_name]).page(params[:page])
    render 'prototypes/index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user =User.find(paramas[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def main_image(prototype)
    prototype.thumbnails[0].content.url
  end
end

app/views/comments/_comment.html.haml
.media
  .media-left
    = link_to image_tag(comment.user.avatar, alt: '64x64', data: { holder: { rendered: 'true'}, src: 'holder.js/64x64'}, style: 'width: 64px; height: 64px;', class: 'media-object'), root_path
  .media-body
    %h4.media-heading
      = comment.user.name
    %p
      = comment.text

app/views/comments/create.js.erb
$('.form-control').val('');
$('#comments').html(
  '<%= j(render partial: 'comments/comment', collection: @prototype.comments) %>'
);
$('span.num').html(
  '(<%= (@prototype.comments.count) %>)'
);

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle{ type: 'button', data: { toggle: 'collapse', target: '.navbar-responsive-collapse' }}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to image_tag('logo.png', alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '36px'), root_path, class: 'navbar-brand'
    .navbar-collapse.collapse.navbar-responsive-collapse
      - unless user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'Get Started', new_user_registration_path
      - else
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{aria: { expanded: 'false'}, data: { toggle: 'dropdown'}, href: '#', role: 'button'}
              = current_user.name
              %span.caret
                %ul.dropdown-menu{ role: 'menu' }
                  %li
                    = link_to 'Profile Edit', edit_user_registration_path
                  %li
                    = link_to 'Log out', destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              = link_to 'New Proto', new_prototype_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ content: 'text/html; charset=US-ASCII', http: { equiv: 'Content-Type' }}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', data: { turbolinks: { track: true }}
    = javascript_include_tag 'application', data: { turbolinks: { track: true }}
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/likes/_like.html.haml
- unless @prototype.like_blank?(current_user)
  = button_tag class: 'btn btn-default' do
    = link_to image_tag('icon_heart_red.svg'), like_path(prototype_id: @prototype.id, id:@prototype.id), method: :delete, remote: true
    Like
    %span#likes_count
      = @prototype.likes_count
- else
  = button_tag class: 'btn btn-default' do
    = link_to image_tag('icon_heart.svg'), likes_path(prototype_id: @prototype.id), method: :post, remote: true
    Like
    %span#likes_count
      = @prototype.likes_count

app/views/likes/create.js.erb
$('#like_form').html(
  '<%= j(render partial: 'likes/like') %>'
);

app/views/likes/destroy.js.erb
$('#like_form').html(
  '<%= j(render partial: 'likes/like') %>'
);

app/views/prototype/index.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag("data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", alt: "64x64", data: { holder: { rendered: "true"}, src: "holder.js/64x64"}, style: "width: 64px; height: 64px;", class: "media-object"), root_path
        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
          .proto-user
            = link_to "by User", ''
            %span.degree we-b inc. Designer
              
    .col-md-6.text-right
      %button.btn.btn-default
        = image_tag "icon_heart.svg"
        Like
        %span.num 20
  .row
    .col-md-9
      = image_tag "sample.png", class: 'img-responsive'
    .col-md-3
      %ul.proto-sub-list.list-group
        %li.list-group-item
          = image_tag "sample.png", class: 'img-responsive'
        %li.list-group-item
          = image_tag "sample.png", class: 'img-responsive'
        %li.list-group-item
          = image_tag "sample.png", class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p Type something
    .col-md-6
      %h4 Concept
      %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        %li 
          = link_to "iPad", root_path, class: "btn btn-default"
        %li 
          = link_to "wireframe", root_path, class: "btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (10) 
    .col-md-8
      .media
        .media-left
          = link_to image_tag("data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", alt: "64x64", data: { holder: { rendered: "true"}, src: "holder.js/64x64"}, style: "width: 64px; height: 64px;", class: "media-object"), root_path

        .media-body
          %h4#top-aligned-media.media-heading
            Top aligned media
            %a.anchorjs-link{ href: "#top-aligned-media" }
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      .media
        .media-left.media-middle
          = link_to image_tag("data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", alt: "64x64", data: { holder: { rendered: "true"}, src: "holder.js/64x64"}, style: "width: 64px; height: 64px;", class: "media-object"), root_path
        .media-body
          %h4#middle-aligned-media.media-heading
            Middle aligned media
            %a.anchorjs-link{ href: "#middle-aligned-media" }
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      .media
        .media-left.media-bottom
          = link_to image_tag("data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", alt: "64x64", data: { holder: { rendered: "true"}, src: "holder.js/64x64"}, style: "width: 64px; height: 64px;", class: "media-object"), root_path
        .media-body
          %h4#bottom-aligned-media.media-heading
            Bottom aligned media
            %a.anchorjs-link{ href: "#bottom-aligned-media" }
              %span.anchorjs-icon
          %p Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          %p Donec sed odio dui. Nullam quis risus eget urna mollis ornare vel eu leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
      %form.form-inline{ role: "form" }
        %h4 Write a comment
        .row
          .form-group.col-md-10
            %textarea.form-control{ placeholder: "Your comments", rows: "3" }
          .form-group.col-md-2
            = button_tag "Comment", class: "btn btn-primary"
            

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to image_tag(main_image(prototype)), prototype_path(prototype)
    .caption
      %h3
        = prototype.name
      .proto-meta
        .proto-user
          = link_to "by #{prototype.user.name}", root_path
        .proto-posted
          Apr 26
      %ul.proto-tag-list.list-inline
        - prototype.tag_list.each do |tag|
          %li
            = link_to tag, tag_path(tag), class: 'btn btn-default'

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag 'header_logo.png', alt: 'PROTO TYPE - SHARE THE PROTOTYPE', height: '73px'

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.sort_tab.popular.active{ role: 'presentation' }
          = link_to 'Popular PROTO', popular_prototypes_path, remote: true
        %li.sort_tab.newest{ role: 'presentation' }
          = link_to 'Newest PROTO', newest_prototypes_path, remote: true
      = button_to 'View Tags', tags_path,method: :get, class: 'btn btn-default col-lg-1 view_tag'

.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    %li.disabled
      = paginate(@prototypes)

app/views/prototypes/newest.js.erb
$('.proto-list .row').html(
  '<%= j(render partial: 'prototypes/prototype', collection: @prototypes) %>'
);
$('li.sort_tab.newest').addClass('active');
$('li.sort_tab.popular').removeClass('active');

app/views/prototypes/popular.js.erb
$('.proto-list .row').html(
  '<%= j(render partial: 'prototypes/prototype', collection: @prototypes) %>'
);
$('li.sort_tab.popular').addClass('active');
$('li.sort_tab.newest').removeClass('active');

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to image_tag(@prototype.user.avatar, alt: '64x64', data: { holder: { rendered: 'true'}, src: 'holder.js/64x64'}, style: 'width: 64px; height: 64px;', class: 'media-object'), root_path
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.name
          .proto-user
            = link_to "by #{@prototype.user.name}", ''
            %span.degree
              = @prototype.user.group + ' ' + @prototype.user.works
    .col-md-6.text-right
      #like_form
        = render partial: 'likes/like'
  .row
    .col-md-9
      = image_tag main_image(@prototype), class: 'img-responsive'
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.thumbnails.sub.each do |proto_thumbnails|
          %li.list-group-item
            = image_tag proto_thumbnails.content.url, class: 'img-responsive'
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tag_list.each do |tag|
          %li
            = link_to tag, tag_path(tag), class: 'btn btn-default'
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num (#{@prototype.comments.count})
    .col-md-8
      #comments
        = render @prototype.comments
      - if user_signed_in?
        = form_for @comment, html: { class: 'form-inline' }, remote: true do |f|
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :text, placeholder: 'Your comments', rows: '3', class: 'form-control'
              = f.hidden_field :prototype_id, value: @prototype.id
            .form-group.col-md-2
              = f.submit 'Comment', class: 'btn btn-primary'

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2 Tags list
      %ul
        - @tags.each do |tag|
          %li.col-md-4
            = link_to tag, tag_path(tag.name), class: 'btn btn-default'

app/views/user/index.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{href: "#"}
          %img.media-object{ alt: "64x64", data: { holder: { rendered: "true", { src: "holder.js/64x64"}}}, src: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSI2NCIgaGVpZ2h0PSI2NCIgZmlsbD0iI0VFRUVFRSIvPjxnPjx0ZXh0IHg9IjEzLjQ2MDkzNzUiIHk9IjMyIiBzdHlsZT0iZmlsbDojQUFBQUFBO2ZvbnQtd2VpZ2h0OmJvbGQ7Zm9udC1mYW1pbHk6QXJpYWwsIEhlbHZldGljYSwgT3BlbiBTYW5zLCBzYW5zLXNlcmlmLCBtb25vc3BhY2U7Zm9udC1zaXplOjEwcHQ7ZG9taW5hbnQtYmFzZWxpbmU6Y2VudHJhbCI+NjR4NjQ8L3RleHQ+PC9nPjwvc3ZnPg==", style: "width: 64px; height: 64px;" }/
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree we-b inc. Designer
        .row
          .col-md-6
            %h4 Profile
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
          .col-md-6
            %h4 Works
            %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
.container.proto-list
  .row
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        = link_to "" do
          = image_tag "sample.png"
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                = link_to "iPad", user_path, class: "btn btn-default"
              %li 
                = link_to "wireframe", user_path, class: "btn btn-default"
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        = link_to "" do
          = image_tag "sample.png"
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                = link_to "iPad", user_path, class: "btn btn-default"
              %li 
                = link_to "wireframe", user_path, class: "btn btn-default"
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        = link_to "" do
          = image_tag "sample.png"
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                = link_to "iPad", user_path, class: "btn btn-default"
              %li 
                = link_to "wireframe", user_path, class: "btn btn-default"
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        = link_to "" do
          = image_tag "sample.png"
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                = link_to "iPad", user_path, class: "btn btn-default"
              %li 
                = link_to "wireframe", user_path, class: "btn btn-default"
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        = link_to "" do
          = image_tag "sample.png"
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                = link_to "iPad", user_path, class: "btn btn-default"
              %li 
                = link_to "wireframe", user_path, class: "btn btn-default"
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        = link_to "" do
          = image_tag "sample.png"
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                = link_to "iPad", user_path, class: "btn btn-default"
              %li 
                = link_to "wireframe", user_path, class: "btn btn-default"
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        %a{href: ""}
          = image_tag "sample.png"
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                = link_to "iPad", user_path, class: "btn btn-default"
              %li 
                = link_to "wireframe", user_path, class: "btn btn-default"
    .col-sm-4.col-md-3.proto-content
      .thumbnail
        = link_to "" do
          = image_tag "sample.png"
          .caption
            %h3 Salvation Army on iPad App Wireframe
            .proto-meta
              .proto-date
                Apr 26
            %ul.proto-tag-list.list-inline
              %li 
                = link_to "iPad", user_path, class: "btn btn-default"
              %li 
                = link_to "wireframe", user_path, class: "btn btn-default"
                
.text-center
  %ul.pagination
    %li.disabled
      %a{"aria-label" => "Previous", :href => "#"}
        %span{ aria: { hidden: "true"}} «
    %li.active
      %a{:href => "#"}
        1
        %span.sr-only (current)
    %li
      = link_to "2", user_path
    %li
      = link_to "3", user_path
    %li
      = link_to "4", user_path
    %li
      = link_to "5", user_path
    %li
      %a{"aria-label" => "Next", :href => "#"}
        %span{ aria: { hidden: "true"}} »